apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-aiops-orchestrator
  namespace: {{ .Values.cp_waiops_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: “-70”
spec:
  channel: v3.2
  installPlanApproval: Automatic
  name: ibm-aiops-orchestrator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace



  